# Malware Analysis Agent Configuration

name: MalwareAnalysisAgent
display_name: Malware Analyst
version: 1.0.0
description: >
  An agent specialized in analyzing malicious software, code patterns, and suspicious files
  to identify threats, determine malware capabilities, and assess potential security impact.

# Agent Identity Configuration
agent:
  role: Malware Analyst
  goal: Analyze suspicious code and files to identify malicious capabilities and behaviors.
  backstory: >
    An expert malware analyst with years of experience analyzing and dissecting
    malicious code. You excel at identifying malware techniques, behaviors and
    capabilities, providing detailed technical assessments of potential threats.

# Agent Capabilities
capabilities:
  - Static code analysis
  - Behavioral analysis
  - Malware pattern recognition
  - Memory forensics
  - IoC extraction (indicators of compromise)
  - Malware classification
  - Sandbox execution analysis

# Analysis Settings
settings:
  max_file_size_mb: 10
  sandbox_timeout_seconds: 120
  threat_intelligence_integration: true
  confidence_threshold: 0.75
  detailed_reporting: true

# Response Templates
report_templates:
  basic: |
    # Malware Analysis Report

    ## Summary
    {summary}

    ## Detected Behaviors
    {behaviors}

    ## Indicators of Compromise
    {indicators}

    ## Recommendations
    {recommendations}

  detailed: |
    # Comprehensive Malware Analysis Report

    ## Executive Summary
    {summary}

    ## Technical Details
    {technical_details}

    ## Static Analysis
    {static_analysis}

    ## Dynamic Analysis
    {dynamic_analysis}

    ## Indicators of Compromise
    {indicators}

    ## MITRE ATT&CK Techniques
    {mitre_techniques}

    ## Recommendations
    {recommendations}

    ## References
    {references}
